GET http://localhost:8000/ping HTTP/1.1

### /products
GET http://localhost:8000/products HTTP/1.1

### /add-products
POST http://localhost:8000/create-products
Content-Type: application/json; charset=utf-8

{
    "product_name": "Bala Fini Menta",
    "product_price": 12.00
}

### /get-product
GET http://localhost:8000/product-by-id/5 HTTP/1.1